language: bash

os:
  - linux
  - osx

matrix:
  fast_finish: true
  allow_failures:
      - os: osx
script:
#  - shellcheck --shell=bash --exclude=SC1090,SC1091,SC2034,SC2059,SC2046 bashrc bash_profile bash_aliases bash_functions bash_prompt
  - if [[ "$TRAVIS_OS_NAME" = "linux" ]]; then    shellcheck install.sh ; fi
  - bash -xv ./install.sh -nv
