language: bash
os:
  - linux
  - osx
before_install:
  - | 
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; 
    then
      brew update >/dev/null
      brew install shellcheck
    fi
script:
#  - shellcheck --shell=bash --exclude=SC1090,SC1091,SC2034,SC2059,SC2046 bashrc bash_profile bash_aliases bash_functions bash_prompt
  - shellcheck install.sh
  - ./install.sh
matrix:
  fast_finish: true
